import React, { useState } from "react";
import { PageHeading } from "../components/common.jsx";
import { accuracyTone, bookName, dateKey, dateLabel, fmt, isAttempted, isSolved, questionCount, questionsForAverage, rate, todayKey, totalTime } from "../lib/study.js";
export default function CalendarPage({sessions,books,selectedDate,month,onSelect,onMonth,onPlan,onOpen,onMove}){
  const [calendarMode,setCalendarMode]=useState("day");
  const year=month.getFullYear(),monthIndex=month.getMonth(),first=new Date(year,monthIndex,1).getDay(),days=new Date(year,monthIndex+1,0).getDate();
  const title=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long"}).format(month);
  const keys=Array.from({length:days},(_,i)=>dateKey(year,monthIndex,i+1));
  const selectedSessions=sessions.filter((s)=>s.date===selectedDate);
  const monthPrefix=year+"-"+String(monthIndex+1).padStart(2,"0"),monthly=sessions.filter((s)=>s.date.startsWith(monthPrefix));
  const monthDays={};monthly.forEach((session)=>{const day=monthDays[session.date]||(monthDays[session.date]={date:session.date,seconds:0,total:0,solved:0,skipped:0,graded:0,correct:0,books:[]});day.seconds+=totalTime(session);day.total+=session.questions.length;day.solved+=session.questions.filter(isAttempted).length;day.skipped+=session.questions.filter((q)=>q.result==="skipped").length;day.graded+=session.questions.filter((q)=>q.result==="correct"||q.result==="wrong").length;day.correct+=session.questions.filter((q)=>q.result==="correct").length;const name=bookName(books,session.bookId);if(!day.books.includes(name))day.books.push(name);});
  const monthDaysList=Object.values(monthDays).sort((a,b)=>b.date.localeCompare(a.date)),monthTotalSeconds=monthDaysList.reduce((sum,day)=>sum+day.seconds,0),monthTotalSolved=monthDaysList.reduce((sum,day)=>sum+day.solved,0),monthTotalSkipped=monthDaysList.reduce((sum,day)=>sum+day.skipped,0),monthTotal=monthDaysList.reduce((sum,day)=>sum+day.total,0),monthGraded=monthDaysList.reduce((sum,day)=>sum+day.graded,0),monthCorrect=monthDaysList.reduce((sum,day)=>sum+day.correct,0),monthAccuracy=rate(monthCorrect,monthGraded),monthStudyDays=monthDaysList.filter((day)=>day.seconds>0||day.solved>0||day.skipped>0).length;
  function shiftMonth(offset){const next=new Date(year,monthIndex+offset,1);onMonth(next);const selected=new Date(selectedDate+"T12:00:00");if(selected.getFullYear()!==next.getFullYear()||selected.getMonth()!==next.getMonth())onSelect(dateKey(next.getFullYear(),next.getMonth(),1));}
  return <section className="view calendar-view">
    <PageHeading eyebrow="YOUR STUDY CALENDAR" title="공부 달력" subtitle="날짜별로 어떤 문제집을 풀었는지 모아봐요." action={<button className="primary" onClick={onPlan}>＋ 이 날짜에 계획</button>}/>
    <div className="calendar-card">
      <div className="calendar-toolbar"><button className="month-arrow" onClick={()=>shiftMonth(-1)} aria-label="이전 달">‹</button><h2>{title}</h2><button className="month-arrow" onClick={()=>shiftMonth(1)} aria-label="다음 달">›</button><button className="today-link" onClick={()=>{const d=new Date();onMonth(new Date(d.getFullYear(),d.getMonth(),1));onSelect(todayKey());}}>오늘</button></div>
      <div className="calendar-grid weekday-grid">{["일","월","화","수","목","금","토"].map((day,i)=><span className={i===0?"sunday":""} key={day}>{day}</span>)}</div>
      <div className="calendar-grid day-grid">{Array.from({length:first},(_,i)=><div className="calendar-blank" key={"blank-"+i}/>)}{keys.map((key,index)=>{const daySessions=sessions.filter((s)=>s.date===key);return <button key={key} className={"calendar-day "+(key===selectedDate?"selected ":"")+(key===todayKey()?"today":"")} onClick={()=>onSelect(key)} aria-label={dateLabel(key)+(daySessions.length?" · "+daySessions.length+"개 문제집 풀이":"")}><b>{index+1}</b>{daySessions.length>0&&<div className="calendar-book-names">{daySessions.slice(0,2).map((s)=><span key={s.id}>{bookName(books,s.bookId)}</span>)}{daySessions.length>2&&<small>+{daySessions.length-2}</small>}</div>}</button>;})}</div>
      <div className="calendar-legend"><span><i/> 풀이가 있는 날</span><span>{sessions.filter((s)=>s.date.startsWith(year+"-"+String(monthIndex+1).padStart(2,"0"))).length}개 풀이 계획</span></div>
    </div>
    <div className="selected-day-heading"><div><div className="eyebrow">{calendarMode==="day"?"SELECTED DAY":"MONTHLY SUMMARY"}</div><h2>{calendarMode==="day"?dateLabel(selectedDate):title}</h2></div><div className="calendar-report-controls"><div className="calendar-report-tabs" role="tablist" aria-label="달력 기록 보기"><button className={calendarMode==="day"?"active":""} onClick={()=>setCalendarMode("day")}>선택한 날</button><button className={calendarMode==="month"?"active":""} onClick={()=>setCalendarMode("month")}>이번 달</button></div>{calendarMode==="day"&&<button className="subtle" onClick={onPlan}>＋ 문제집 추가</button>}</div></div>
    {calendarMode==="day"?(!selectedSessions.length?<div className="day-empty"><span>▦</span><div><b>이 날짜에는 등록된 풀이가 없어요.</b><p>문제집과 페이지 범위를 정해 계획을 추가해보세요.</p></div></div>:<div className="calendar-report-wrap"><table className="calendar-report"><thead><tr><th>문제집</th><th>정답률</th><th>풀이시간(평균)</th><th>진행</th></tr></thead><tbody>{selectedSessions.map((session)=><CalendarReportRow key={session.id} session={session} books={books} onOpen={()=>onOpen(session)} onMove={onMove}/>)}</tbody></table></div>):!monthDaysList.length?<div className="day-empty"><span>▦</span><div><b>{title} 풀이 기록이 없어요.</b><p>이 달의 풀이 기록이 생기면 여기에 모아볼 수 있어요.</p></div></div>:<><div className="report-summary-grid calendar-month-summary"><article><span>순공 시간</span><b>{Math.floor(monthTotalSeconds/3600)}<small>시간</small> {String(Math.floor(monthTotalSeconds/60)%60).padStart(2,"0")}<small>분</small></b></article><article><span>공부한 날</span><b>{monthStudyDays}<small>일</small></b></article><article><span>푼 문항 (건너뜀)</span><b>{questionCount(monthTotalSolved,monthTotalSkipped,monthTotal)}</b></article><article className={accuracyTone(monthAccuracy)}><span>정답률</span><b>{monthAccuracy===null?"—":monthAccuracy+"%"}</b></article></div><div className="calendar-report-wrap"><table className="calendar-report report-daily-table"><thead><tr><th>날짜</th><th>문제집</th><th>풀이(건너뜀)/전체</th><th>공부 시간</th></tr></thead><tbody>{monthDaysList.map((day)=><tr key={day.date}><td className="report-date"><button className="report-date-link" onClick={()=>{onSelect(day.date);setCalendarMode("day");}}>{Number(day.date.slice(-2))}일</button></td><td className="report-daily-books" title={day.books.join(", ")}>{day.books.join(", ")}</td><td className="report-daily-count">{questionCount(day.solved,day.skipped,day.total)}</td><td className="report-time">{fmt(day.seconds)}</td></tr>)}</tbody></table></div></>}
  </section>;
}
function CalendarReportRow({session,books,onOpen,onMove,showDate=false}){
  const finished=session.questions.filter(isAttempted).length,skipped=session.questions.filter((q)=>q.result==="skipped").length;
  const correct=session.questions.filter((q)=>q.result==="correct").length,graded=session.questions.filter((q)=>q.result==="correct"||q.result==="wrong").length,accuracy=graded?rate(correct,graded):null;
  const status=session.status==="done"?(session.questions.some((q)=>q.result==="pending")?"부분 채점":"✅ 완료"):session.status==="grading"?"채점 중":session.status==="active"?"풀이 중":"계획";
  const action=session.status==="done"?"기록 보기":session.status==="grading"?"채점 이어하기":"풀이 열기";
  const averageTime=fmt(Math.round(totalTime(session)/questionsForAverage(session.questions)));
  const name=bookName(books,session.bookId);
  return <tr><td className="report-main-cell" data-label="문제집"><div className="report-book-heading"><strong title={name} aria-label={name}>{name}</strong></div><span className="report-book-range">{showDate&&<>{dateLabel(session.date)} · </>}{session.pageStart}–{session.pageEnd}쪽 · {session.questionStart}–{session.questionEnd}번</span>{session.status==="planned"&&<div className="report-inline-actions"><label>날짜 변경<input type="date" value={session.date} onChange={(e)=>onMove(session.id,e.target.value)}/></label></div>}</td><td data-label="정답률" className={"report-accuracy "+accuracyTone(accuracy)}>{accuracy===null?"—":accuracy+"%"}</td><td data-label="풀이시간(평균)" className="report-time">{averageTime}</td><td data-label="진행"><div className="report-progress"><b>{questionCount(finished,skipped,session.questions.length)} {status}</b><button className="outline" onClick={onOpen}>{action} →</button><span className="report-progress-bar"><i style={{width:(finished/Math.max(session.questions.length,1)*100)+"%"}}/></span></div></td></tr>;
}
