import React from "react";
import { PageHeading } from "../components/common.jsx";
import Notes from "../components/Notes.jsx";
import { bookName, elapsedSeconds, fmt, isAttempted, questionCount, questionsForAverage, totalTime } from "../lib/study.js";

export function SolvePage({current,books,tick,onBack,onGrade,onStart,onStop,onNext,onSkip,onSelectQuestion}) {
  return <section className="view focus-view"><button className="back-link" onClick={onBack}>← 오늘의 공부</button><div className="focus-heading"><div><div className="eyebrow">FOCUS MODE · {bookName(books,current.bookId)}</div><h1>빠르게 풀고, 정확하게<span>.</span></h1><p>{current.pageStart}–{current.pageEnd}쪽 · 총 {current.questions.length}문제</p></div><div className="focus-tools"><div className="focus-count"><b>{current.currentIndex+1}</b> / {current.questions.length}</div><button className="mid-grade" onClick={onGrade}>{current.questions.some((q)=>q.startedAt)?"타이머 종료 후 채점":"중간 채점하기"}</button></div></div><div className="focus-progress"><div className="progress"><i style={{width:(current.currentIndex/current.questions.length*100)+"%"}}/></div><span>{questionCount(current.questions.filter(isAttempted).length,current.questions.filter((q)=>q.result==="skipped").length,current.questions.length)} 문항</span></div>
        <div className="timer-card"><div className="timer-top"><span><i className={current.questions[current.currentIndex].startedAt?"pulse":""}/>{current.questions[current.currentIndex].startedAt?"집중하는 중":current.questions[current.currentIndex].result==="skipped"?"건너뛴 문항":"현재 문항"}</span><small>{bookName(books,current.bookId)}</small></div><div className="q-number"><small>{current.questions[current.currentIndex].page?`${current.questions[current.currentIndex].page}쪽`:"전체 범위"}</small><b>{current.questions[current.currentIndex].number}<i>번</i></b></div><div className={"timer "+(current.questions[current.currentIndex].startedAt?"running":"")}>{fmt(current.questions[current.currentIndex].seconds+(current.questions[current.currentIndex].startedAt?elapsedSeconds(current.questions[current.currentIndex].startedAt,tick):0))}</div><p className="timer-help">{current.questions[current.currentIndex].startedAt?"다 풀면 종료 버튼을 눌러주세요.":current.questions[current.currentIndex].result==="skipped"?"다시 풀거나, 건너뛴 상태로 둘 수 있어요.":"시작 버튼을 누르면 풀이 시간을 재요."}</p><div className="timer-actions">{current.questions[current.currentIndex].startedAt?<button className="stop" onClick={onStop}>■　종료</button>:<><button className="start" onClick={onStart}>▶　시작</button>{current.questions[current.currentIndex].seconds>0&&<button className="next" onClick={onNext}>{current.currentIndex===current.questions.length-1?"채점하기":"다음 문제"}　→</button>}{current.questions[current.currentIndex].result!=="correct"&&current.questions[current.currentIndex].result!=="wrong"&&<button className="skip" onClick={onSkip}>건너뛰기　→</button>}</>}</div><div className="timer-total"><span>지금까지 푼 시간</span><b>{fmt(totalTime(current,tick))}</b></div></div>
        <div className="q-progress"><h2>문항 진행</h2><p>문항 번호를 눌러 다시 풀 수 있어요. 재풀이 시간은 누적되고, 건너뛴 문항은 채점에서 제외돼요. 이동하려면 타이머를 먼저 종료해주세요.</p><div>{current.questions.map((q,i)=><button type="button" key={q.id} className={i===current.currentIndex?"current":q.result==="skipped"?"skipped":q.seconds>0?"timed":""} aria-label={`${q.number}번 문항${q.result==="skipped"?", 건너뜀":q.seconds>0?`, 기록 ${fmt(q.seconds)}`:""}`} aria-pressed={i===current.currentIndex} disabled={current.questions.some((item)=>item.startedAt)&&i!==current.currentIndex} onClick={()=>onSelectQuestion(i)}>{q.number}</button>)}</div></div></section>;
}

export function GradingPage({current,books,onBack,onHome,onAnswer,onNote,onFinish}) {
  return <section className={"view grading-view "+(current.status==="done"?"record-view":"")}><button className="back-link" onClick={onBack}>{current.status==="done"?"← 오늘의 공부":"← 풀이 화면"}</button><PageHeading eyebrow={(current.status==="done"?"PRACTICE RECORD · ":"CHECK YOUR ANSWERS · ")+bookName(books,current.bookId)} title="이제 채점해볼까요?" subtitle={current.status==="done"?"채점한 결과를 확인하고, 남은 문항도 이어서 채점할 수 있어요.":"채점할 문항만 선택해 저장하세요. 나머지는 나중에 이어서 채점할 수 있어요."} action={<div className="wrong-total">{current.questions.filter((q)=>q.result==="correct"||q.result==="wrong").length}<span>/{current.questions.length} 채점</span></div>}/><div className="grade-summary"><span>문제별 시간 합계 <b>{fmt(totalTime(current))}</b></span><span>평균 풀이 시간 <b>{fmt(Math.round(totalTime(current)/questionsForAverage(current.questions)))}</b></span><span>풀이 문항 <b>{questionCount(current.questions.filter(isAttempted).length,current.questions.filter((q)=>q.result==="skipped").length,current.questions.length)}</b></span></div><div className="grade-list">{current.questions.map((q)=><GradeCard key={q.id} question={q} sessionId={current.id} onAnswer={onAnswer} onNote={onNote}/>)}</div><div className="grade-footer"><span>건너뛴 문항과 미채점 문항은 정답률에서 제외돼요.</span>{current.status==="done"?<button className="primary" onClick={onHome}>오늘의 공부로 <b>→</b></button>:<button className="primary" onClick={onFinish}>채점 결과 저장 <b>→</b></button>}</div></section>;
}
function GradeCard({question,sessionId,onAnswer,onNote}){return <article className={"grade-card "+(question.result==="wrong"?"marked-wrong":"")}><div className="grade-head"><div className="grade-number"><small>{question.page?`${question.page}쪽`:"전체 범위"}</small><b>{question.number}<i>번</i></b></div><div className="grade-time"><small>풀이 시간</small>{question.result==="skipped"?<span className="skipped-label"><span>건너뜀</span><span>채점 제외</span></span>:<b>{fmt(question.seconds)}</b>}</div><div className="answers"><button className={question.result==="correct"?"correct chosen":"correct"} onClick={()=>onAnswer(question.id,"correct")}>✓ 맞았어요</button><button className={question.result==="wrong"?"wrong chosen":"wrong"} onClick={()=>onAnswer(question.id,"wrong")}>× 틀렸어요</button></div></div>{question.result==="wrong"&&<Notes reason={question.reason||""} strategy={question.strategy||""} photo={question.photo||""} save={(field,value)=>onNote(sessionId,question.id,field,value)}/>}</article>;}

