import React, { useEffect, useState } from "react";
import { getValidAccessToken } from "../supabase.js";
import { PageHeading } from "../components/common.jsx";
import { accuracyTone, bookName, dateKey, dateLabel, fmt, isAttempted, isSolved, questionCount, questionsForAverage, rate, totalTime } from "../lib/study.js";
export default function ReportPage({sessions,books}){
  const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1);});
  const [aiFeedback,setAiFeedback]=useState(null),[aiLoading,setAiLoading]=useState(false),[aiError,setAiError]=useState("");
  const year=month.getFullYear(),monthIndex=month.getMonth(),monthPrefix=year+"-"+String(monthIndex+1).padStart(2,"0");
  const monthTitle=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long"}).format(month);
  const monthly=sessions.filter((s)=>s.date.startsWith(monthPrefix)).sort((a,b)=>b.date.localeCompare(a.date));
  const daysInMonth=new Date(year,monthIndex+1,0).getDate();
  const days=Array.from({length:daysInMonth},(_,i)=>({date:dateKey(year,monthIndex,i+1),seconds:0,total:0,solved:0,skipped:0,graded:0,correct:0,books:[]}));
  monthly.forEach((session)=>{const day=days[Number(session.date.slice(-2))-1];if(!day)return;day.seconds+=totalTime(session);day.total+=session.questions.length;day.solved+=session.questions.filter(isAttempted).length;day.skipped+=session.questions.filter((q)=>q.result==="skipped").length;day.graded+=session.questions.filter((q)=>q.result==="correct"||q.result==="wrong").length;day.correct+=session.questions.filter((q)=>q.result==="correct").length;const name=bookName(books,session.bookId);if(!day.books.includes(name))day.books.push(name);});
  const daysWithRecords=days.filter((day)=>day.total>0),activeDays=days.filter((day)=>day.seconds>0||day.solved>0||day.skipped>0),totalSeconds=daysWithRecords.reduce((sum,day)=>sum+day.seconds,0),totalQuestions=daysWithRecords.reduce((sum,day)=>sum+day.total,0),totalSolved=daysWithRecords.reduce((sum,day)=>sum+day.solved,0),totalSkipped=daysWithRecords.reduce((sum,day)=>sum+day.skipped,0),graded=daysWithRecords.reduce((sum,day)=>sum+day.graded,0),correct=daysWithRecords.reduce((sum,day)=>sum+day.correct,0),monthlyAccuracy=rate(correct,graded);
  const bookReports=books.map((book)=>{const bookSessions=monthly.filter((s)=>s.bookId===book.id);if(!bookSessions.length)return null;const questions=bookSessions.flatMap((s)=>s.questions),gradedQuestions=questions.filter((q)=>q.result==="correct"||q.result==="wrong"),right=gradedQuestions.filter((q)=>q.result==="correct").length,solved=questions.filter(isAttempted).length,skipped=questions.filter((q)=>q.result==="skipped").length,seconds=bookSessions.reduce((sum,s)=>sum+totalTime(s),0),averageSeconds=Math.round(seconds/questionsForAverage(questions));return {book,difficulty:book.difficulty||"보통",total:questions.length,solved,skipped,graded:gradedQuestions.length,accuracy:rate(right,gradedQuestions.length),averageSeconds,average:fmt(averageSeconds),studyDays:new Set(bookSessions.filter((s)=>totalTime(s)>0||s.questions.some(isSolved)).map((s)=>s.date)).size};}).filter(Boolean).map((entry,index)=>({...entry,key:`book_${index+1}`}));
  useEffect(()=>{setAiFeedback(null);setAiError("");},[monthPrefix]);
  async function generateAiFeedback(){
    setAiLoading(true);setAiError("");
    try{
      const accessToken=await getValidAccessToken();
      const response=await fetch("/api/report-commentary",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${accessToken}`},body:JSON.stringify({month:monthPrefix,summary:{totalSeconds,studyDays:activeDays.length,accuracy:monthlyAccuracy},books:bookReports.map(({key,difficulty,total,solved,skipped,graded,accuracy,averageSeconds,studyDays})=>({key,difficulty,total,solved,skipped,graded,accuracy,averageSeconds,studyDays}))})});
      let result;
      try{result=await response.json();}catch{throw new Error("AI 코멘트 서버 응답을 읽지 못했어요. 배포 환경 변수와 서버 함수를 확인해주세요.");}
      if(!response.ok){const missing=Array.isArray(result.missing)&&result.missing.length?` (누락: ${result.missing.join(", ")})`:"";throw new Error((result.error||"AI 코멘트를 불러오지 못했어요.")+missing);}
      setAiFeedback(result);
    }catch(error){setAiError(error.message||"AI 코멘트를 불러오지 못했어요.");}
    finally{setAiLoading(false);}
  }
  function shiftMonth(offset){setMonth(new Date(year,monthIndex+offset,1));}
  const maxSeconds=Math.max(1,...days.map((day)=>day.seconds));
  return <section className="view report-view">
    <PageHeading eyebrow="STUDY REPORT" title="레포트" subtitle="이번 달 문제집별 성과와 날짜별 공부 기록을 살펴봐요."/>
    <div className="report-month-toolbar"><button className="month-arrow" onClick={()=>shiftMonth(-1)} aria-label="이전 달">‹</button><h2>{monthTitle}</h2><button className="month-arrow" onClick={()=>shiftMonth(1)} aria-label="다음 달">›</button><button className="today-link" onClick={()=>{const d=new Date();setMonth(new Date(d.getFullYear(),d.getMonth(),1));}}>이번 달</button></div>
    {!monthly.length?<div className="day-empty"><span>▧</span><div><b>{monthTitle} 풀이 기록이 없어요.</b><p>문제 풀이를 시작하면 월간 레포트가 여기에 모여요.</p></div></div>:<>
      <div className="report-summary-grid"><article><span>순공 시간</span><b>{Math.floor(totalSeconds/3600)}<small>시간</small> {String(Math.floor(totalSeconds/60)%60).padStart(2,"0")}<small>분</small></b></article><article><span>공부한 날</span><b>{activeDays.length}<small>일</small></b></article><article><span>푼 문항 (건너뜀)</span><b>{questionCount(totalSolved,totalSkipped,totalQuestions)}</b></article><article className={accuracyTone(monthlyAccuracy)}><span>정답률</span><b>{monthlyAccuracy===null?"—":monthlyAccuracy+"%"}</b></article></div>
      <section className="report-ai-card"><div className="report-ai-heading"><span className="report-ai-icon">✦</span><div><h2>AI 선생님 코멘트</h2><p>문제집 난이도와 이번 달 풀이 통계를 바탕으로 조언을 받아봐요.</p></div><button className="primary" onClick={generateAiFeedback} disabled={aiLoading||!bookReports.length}>{aiLoading?"코멘트 만드는 중…":aiFeedback?"다시 받기":"코멘트 받기"}</button></div><small className="report-ai-privacy">문제집 이름, 오답 메모, 사진은 AI에 보내지 않아요. 익명 통계와 난이도만 사용해요.</small>{aiError&&<p className="report-ai-error" role="alert">{aiError}</p>}{aiFeedback&&<div className="report-ai-results"><p className="report-ai-overall">{aiFeedback.overall}</p>{bookReports.map((entry)=><article key={entry.key}><b>{entry.book.name}</b><p>{aiFeedback.comments.find((comment)=>comment.key===entry.key)?.comment||"이 문제집은 아직 코멘트가 없어요."}</p></article>)}</div>}</section>
      <section className="report-section"><div className="report-section-heading"><div><h2>날짜별 공부 시간</h2><p>문항별 풀이 시간을 합산했어요.</p></div></div><div className="report-chart"><svg viewBox="0 0 700 170" preserveAspectRatio="none" role="img" aria-label={monthTitle+" 날짜별 공부 시간 그래프"}><line x1="8" y1="142" x2="696" y2="142"/><line x1="8" y1="96" x2="696" y2="96"/><line x1="8" y1="50" x2="696" y2="50"/>{days.map((day,index)=>{const barWidth=14,gap=8,x=12+index*(barWidth+gap),height=day.seconds?Math.max(3,day.seconds/maxSeconds*110):0,y=142-height;return <g key={day.date}><title>{dateLabel(day.date)} · {fmt(day.seconds)} · 문항 {questionCount(day.solved,day.skipped,day.total)}</title>{height>0&&<rect x={x} y={y} width={barWidth} height={height} rx="4"/>}{(index===0||(index+1)%5===0||index===days.length-1)&&<text x={x+barWidth/2} y="162" textAnchor="middle">{index+1}</text>}</g>;})}</svg></div></section>
      <section className="report-section"><div className="report-section-heading"><div><h2>문제집별 성과</h2><p>이번 달 풀이 기록을 문제집별로 모았어요.</p></div></div><div className="calendar-report-wrap"><table className="calendar-report report-book-table"><thead><tr><th>문제집</th><th>정답률</th><th>풀이시간(평균)</th><th>풀이(건너뜀)/전체</th></tr></thead><tbody>{bookReports.map(({book,total,solved,skipped,accuracy,average})=><tr key={book.id}><td className="report-main-cell"><div className="report-book-heading"><strong title={book.name}>{book.name}</strong></div><span className="report-book-range">{monthly.filter((s)=>s.bookId===book.id).length}회 풀이</span></td><td className={"report-accuracy "+accuracyTone(accuracy)}>{accuracy===null?"—":accuracy+"%"}</td><td className="report-time">{average}</td><td className="report-progress-cell"><b>{questionCount(solved,skipped,total)}</b><span className="report-progress-bar"><i style={{width:(solved/Math.max(total,1)*100)+"%"}}/></span></td></tr>)}</tbody></table></div></section>
      <section className="report-section"><div className="report-section-heading"><div><h2>날짜별 기록</h2><p>하루 공부 시간과 실제 풀이·건너뜀 문항 수를 확인해요.</p></div></div><div className="calendar-report-wrap"><table className="calendar-report report-daily-table"><thead><tr><th>날짜</th><th>문제집</th><th>풀이(건너뜀)/전체</th><th>공부 시간</th></tr></thead><tbody>{[...daysWithRecords].reverse().map((day)=><tr key={day.date}><td className="report-date">{Number(day.date.slice(-2))}일</td><td className="report-daily-books" title={day.books.join(", ")}>{day.books.join(", ")}</td><td className="report-daily-count">{questionCount(day.solved,day.skipped,day.total)}</td><td className="report-time">{fmt(day.seconds)}</td></tr>)}</tbody></table></div></section>
    </>}
  </section>;
}
